{% set name = "dagger-io" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dagger_io-{{ version }}.tar.gz
  sha256: ec43c6be0ffedec7a822c0c5192b4f5a968ff9b06aacf90d78c013f293d034be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - pip
    - poetry
  run:
    - python >=3.10,<4.0
    - anyio >=3.6.2
    - attrs >=22.1.0
    - cattrs >=22.2.0
    - graphql-core >=3.2.3
    - gql >=3.4.0
    - httpx >=0.23.1
    - rich >=12.6.0
    - typer >=0.6.1
    - beartype >=0.11.0
    - platformdirs >=2.6.2

test:
  imports:
    - dagger
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://dagger.io
  summary: A client package for running Dagger pipelines in Python.
  description: |
    The Dagger Python SDK contains everything you need to develop CI/CD 
    pipelines in Python, and run them on any OCI-compatible container runtime.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.dagger.io/sdk/python
  dev_url: https://github.com/dagger/dagger/tree/main/sdk/python

extra:
  recipe-maintainers:
    - helderco
