{% set name = "dagger-io" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dagger_io-{{ version }}.tar.gz
  sha256: 86d82ee8175fda137d97a4a1869bb78ce2fd4625419c8076fdf7f9da89c8f83e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.10,<4.0
    - anyio >=3.6.2
    - cattrs >=22.2.0
    - graphql-core >=3.2.3
    - gql >=3.4.0
    - httpx >=0.23.1
    - typing_extensions >=4.8.0
    - beartype >=0.11.0
    - platformdirs >=2.6.2
    - rich >=12.6.0

test:
  imports:
    - dagger
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://dagger.io
  summary: A client package for running Dagger pipelines in Python.
  description: |
    The Dagger Python SDK contains everything you need to develop CI/CD
    pipelines in Python, and run them on any OCI-compatible container runtime.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.dagger.io/sdk/python
  dev_url: https://github.com/dagger/dagger/tree/main/sdk/python

extra:
  recipe-maintainers:
    - helderco
