{% set name = "dagger-io" %}
{% set version = "0.13.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dagger_io-{{ version }}.tar.gz
  sha256: d761bdb7ff8207bf8b90d8e9a32b570e157c10e1de90a813afd6d76b7077dbcb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.10,<4.0
    - anyio >=3.6.2
    - cattrs >=22.2.0
    - gql >=3.5.0
    - httpx >=0.23.1
    - beartype >=0.18.2
    - platformdirs >=2.6.2
    - typing_extensions >=4.8.0
    - rich >=12.6.0
    - opentelemetry-sdk >=1.23.0
    - opentelemetry-exporter-otlp-proto-grpc >=1.23.0

test:
  imports:
    - dagger
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://dagger.io
  summary: A client package for running Dagger pipelines in Python.
  description: |
    The Dagger Python SDK contains everything you need to develop CI/CD
    pipelines in Python, and run them on any OCI-compatible container runtime.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.dagger.io/sdk/python
  dev_url: https://github.com/dagger/dagger/tree/main/sdk/python

extra:
  recipe-maintainers:
    - helderco
